version: '3'
services:
  thammask-db:
    image: postgres:11.3-alpine
    container_name: thammask-db
    env_file: .env.production
    volumes:
    - ./volumes/data:/var/lib/postgresql/data
    networks:
    - internal
    labels:
    - traefik.enable=false
    restart: always

  thammask-django:
    build: ./tucovid
    command: sh /thammask/runserver.sh
    container_name: thammask-django
    env_file: .env.production
    depends_on:
    - thammask-db
    labels:
    - traefik.backend=thammask-django
    - traefik.docker.network=proxy
    - traefik.frontend.rule=Host:thammask.storemesh.com;PathPrefix:/
    - traefik.port=8000
    networks:
    - internal
    - proxy
    restart: always
    volumes:
    - ./tucovid:/thammask
    - ./volumes/static:/static
    - ./volumes/media:/media

  thammask-nginx:
    image: nginx:alpine
    container_name: thammask-nginx
    volumes:
    - ./volumes/static:/usr/share/nginx/html/static
    - ./volumes/media:/usr/share/nginx/html/media
    networks:
    - internal
    - proxy
    labels:
    - traefik.backend=thammask-nginx
    - traefik.docker.network=proxy
    - traefik.enable=true
    - traefik.frontend.rule=Host:thammask.storemesh.com;PathPrefix:/static/,/media/
    - traefik.port=80
    depends_on:
    - thammask-django
    restart: always

networks:
  internal:
    external: false
  proxy:
    external: true