# Generated by Django 2.0.7 on 2020-03-18 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Shipping', 'Shipping'), ('Cancel', 'Cancel')], default='Shipping', max_length=100)),
                ('note', models.TextField()),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('thai_citizen_id', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=255)),
                ('holding_medical_license_no', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=500)),
                ('tel_organization', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Wait for verify', 'Wait for verify'), ('Verified', 'Verified'), ('Packing', 'Packing'), ('Shipping', 'Shipping'), ('Confirm received', 'Confirm received')], default='Wait for verify', max_length=100)),
                ('shipping_address', models.TextField()),
                ('shipping_id', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.Item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('receive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donate.Receive')),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.Item'),
        ),
    ]
