# Generated by Django 3.0.4 on 2020-03-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel_organization',
        ),
    ]
