# Generated by Django 2.0.7 on 2020-03-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20200326_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='quantity',
        ),
    ]
