# Generated by Django 3.0.4 on 2020-03-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_remove_receive_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
