# Generated by Django 3.0.4 on 2020-03-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_donateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.DonateItem'),
        ),
    ]
