# Generated by Django 3.0.4 on 2020-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20200402_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateitem',
            name='show_item',
            field=models.BooleanField(default=True),
        ),
    ]
