# Generated by Django 3.0.4 on 2020-04-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_donateitem_show_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='tel',
        ),
    ]
