# Generated by Django 3.0.4 on 2020-04-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_remove_donate_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
