# Generated by Django 3.0.4 on 2020-04-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='holding_medical_license_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='created_by',
        ),
        migrations.AddField(
            model_name='receive',
            name='holding_medical_license_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receive',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Job'),
        ),
        migrations.AddField(
            model_name='receive',
            name='organization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Profile'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Profile'),
        ),
    ]
