# Generated by Django 3.0.4 on 2020-04-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_auto_20200402_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='receive',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Hospital'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Item'),
        ),
    ]
