# Generated by Django 3.0.4 on 2020-04-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_auto_20200402_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='shipping_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
