# Generated by Django 3.0.4 on 2020-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_auto_20200403_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='status',
            field=models.CharField(choices=[('Wait for verify', 'Wait for verify'), ('Verified', 'Verified'), ('Printing', 'Printing'), ('Packing', 'Packing'), ('Shipping', 'Shipping'), ('Confirm received', 'Confirm received')], default='Wait for verify', max_length=100),
        ),
    ]
