# Generated by Django 3.0.4 on 2020-04-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0016_auto_20200403_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='status',
            field=models.CharField(choices=[('รอการผลิต', 'Waiting for production'), ('กำลังบรรจุ', 'Packing'), ('กำลังจัดส่ง', 'Shipping'), ('ยืนยันการรับของ', 'Confirm received')], default='รอการผลิต', max_length=100),
        ),
    ]
