# Generated by Django 3.0.4 on 2020-04-03 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0018_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
