# Generated by Django 3.0.4 on 2020-04-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0019_receive_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive',
            old_name='url',
            new_name='unique_id',
        ),
    ]
