# Generated by Django 3.0.4 on 2020-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0024_receive_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
