# Generated by Django 3.0.4 on 2020-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0025_receive_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
