# Generated by Django 3.0.4 on 2020-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0026_receive_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='hospital',
        ),
        migrations.AddField(
            model_name='receive',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
