# Generated by Django 3.0.4 on 2020-04-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0028_receive_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='hospital',
        ),
    ]
